#pragma once
double Bai_16(int a, int b);
double Bai_17(int a, int b);
double Bai_18(int a, int b);
double Bai_19(int a, int b);
void Bai_20(int a);
void Bai_21(int a);
void Bai_22(int a);
int Bai_23(int a);
void Bai_24(int a);
void Bai_25(int a);
void Bai_26(int a);
void Bai_27(int a);
void Bai_28(int a);
void Bai_29(int a);
void Bai_30(int a);
int Bai_31(int a);
void Bai_32(int a);
double Bai_33(int a);
double Bai_34(int a);
double Bai_35(int a);
double Bai_36(int a);
double Bai_38(int a);
double Bai_39(int a);
double Bai_40(int a, int b);
double Bai_41(int a);
int Bai_42(int a);
int Bai_43(int a);
void Bai_44(int a);
void Bai_45(int a);
void Bai_46(int a);
void Bai_47(int a);
void Bai_48(int a);
void Bai_49(int a);
int Bai_50(int a);
void Bai_51(int a);
void Bai_52(int a);
void Bai_53(int a);
void Bai_54(int a);
void Bai_55(int a);
void Bai_56(int a);
void Bai_59(int a);
void Bai_60(int a);
void Bai_61(int a);
int Bai_62(int a, int b);
void Bai_63(int a, int b);
void Bai_64(int a, int b);
void Bai_65(int a, int b, int c);
void Bai_67(int a, int b);
void Bai_68(int a, int b);
int Congdon(int a);
void Bai_69(int a, int b);
void Bai_70(int a);
void Bai_71(int a, int b);

//MANG 1 CHIEU
void Nhapmang(int a[100], int& n);
void Xuatmang(int a[100], int n);
int GTLN(int a[100], int n);
int GTNN(int a[100], int n);
int NhoHon2004(int a[100], int n);
bool SoNguyenTo(int n);
int SoNguyenToNhoHon100(int a[100], int n);
double TongGiaTriAm(const int a[100], int n);
double TrungBinhCongSNT(int a[100], int& n);
int SoNguyenToLonNhat(int a[100], int& n);
int giaTriAmLonNhat(int a[100], int& n);
int giaTriAmNhoNhat(int a[100], int& n);
int thongKePhanTu(int a[100], int& n);
int demMangCon(int a[100], int& n, int b[100], int& h);